version: "3.3"

services:
  keen-nginx:
    image: nginx:1.25.2-perl
    restart: always
    networks:
      - traefik_network
    volumes:
    - ./public:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keen.rule=Host(`keen.antoine-libert.com`)"
      - "traefik.http.routers.keen.entrypoints=web, websecure"
      - "traefik.http.routers.keen.tls=true"
      - "traefik.http.routers.keen.tls.certresolver=letsencrypt"
      - "traefik.http.services.keen.loadbalancer.server.port=80"

networks:
  traefik_network:
    external: true